### ISSUE TITLE
Doesn't link

### ISSUE THREAD

**Issue by andreheijstek** [calebhc/MoMoney#1]
Hello,
I tried to get this working, but ran into several issues:
1. Rakefile is somewhat outdated:
/usr/bin/rake
Warning:[rake --tasks] require 'motion/project' is deprecated, please require 'motion/project/template/ios' instead
Warning:[rake --prereqs] require 'motion/project' is deprecated, please require 'motion/project/template/ios' instead
That was easily fixed.

2. Something with i386 ?
Macbook-Pro-Andre-51:MoMoney andreheijstek$ rake
     Build ./build/iPhoneSimulator-8.1-Development
     Build vendor/Frank
      Link ./build/iPhoneSimulator-8.1-Development/MoMoney.app/MoMoney
Undefined symbols for architecture i386:
  "_OBJC_IVAR_$_UITouch._gestureView", referenced from:
      -[UITouch(KIFAdditions) initAtPoint:inWindow:] in libFrank.a(UITouch-KIFAdditions.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
rake aborted!
Command failed with status (1): [/Applications/Xcode.app/Contents/Developer...]
/Library/RubyMotion/lib/motion/project/builder.rb:322:in `build'
/Library/RubyMotion/lib/motion/project/app.rb:78:in `build'
/Library/RubyMotion/lib/motion/project/template/ios.rb:68:in `block (2 levels) in <top (required)>'
/Library/RubyMotion/lib/motion/project/template/ios.rb:187:in `block in <top (required)>'
Tasks: TOP => build:simulator
(See full trace by running task with --trace)

Is this also easy to fix?

**Comment by calebhc** [comment]
Hey! :) Sorry the project isn't compiling. I haven't used Ruby Motion in over a year now so I probably won't be of much help. It appears the issue is with KIF. I actually just found a resolved issue for the problem. It appears you need to use an updated version of Frank. https://github.com/kif-framework/KIF/issues/298

I haven't checked on Frank in a while so hopefully they've released a new version. When I get some time I'll try and update the repo so this error doesn't happen again. :)

**Comment by andreheijstek** [comment]
Hi Caleb,

Thanks a lot!
One other question, in topics around using Frank for OSX development, people refer to a blog you have written. But I can’t find that blog anywhere. Is there a new location?

Regards, André

**Comment by calebhc** [comment]
Oops sorry. :) Here's the blog post. http://calebcohoon.blogspot.com/2012/06/test-rubymotion-apps-using-cucumber.html

**Comment by andreheijstek** [comment]
Thanks!

Regards, André
